name: Deploy to NuGet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Deploy to NuGet
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh ${{ secrets.NUGET_API_KEY }}
        working-directory: ./working/content/QmeraApi
